# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: V/LineCars
email: vlinecars@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 VLineCars.com endeavours to provide interesting and detailed information regarding the operations of V/Line services, along with the several types of locomotives, railcars and rollingstock V/Line uses in its day to day operations. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.vlinecars.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:title.html
twitter_username: vlinecars
facebook_username: vlinecars
paginate: 10
paginate_path: "/articles/page:num/"

# Build settings
markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
